#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

# Install nginx
sudo apt-get update
sudo apt-get -y install nginx

# configure nginx to listen on port 80
sudo ufw allow 'Nginx HTTP'

# Creating Sample Page
echo "Hello World!" | sudo tee /var/www/html/index.html

# configures an Nginx server so that /redirect_me is redirecting to another page
sudo sed -i '37i\rewrite ^/redirect_me http://driiis.tech permanent;' /etc/nginx/sites-available/default

# code for error page 
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html

# configures an Nginx server so that /error_page 404 is redirecting to error page 
sudo sed -i '38i\error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# code for http_response_header
sudo sed -i '/^http {/a \\tadd_header X-Served-By $hostname;' /etc/nginx/nginx.conf

# Reload Nginx
sudo service nginx restart
