#!/usr/bin/env bash
# Installs and configure HAproxy on the lb-01 server
# using roundrobin algorithm

sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure HAProxy using roundrobin algorithm
sudo echo "
frontend titosco.tech-frontend
        bind *:80
        mode http
        default_backend titosco.tech-backend

backend titosco.tech-backend
        balance roundrobin
        server 469316-web-01 54.237.57.48 check
        server 469316-web-02 54.145.241.161 check
">> /etc/haproxy/haproxy.cfg

# Enable HAProxy management
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

sudo service haproxy restart
